
const navItems = [...document.querySelectorAll('.nav-item')];
const views = [...document.querySelectorAll('.view')];
const title = document.getElementById('pageTitle');
const subtitle = document.getElementById('pageSubtitle');
const pageMeta = {
 home:['Good Evening, Ethan ✦','One strategic decision requires your attention today.'],
 stories:['Story Repository','Discover, preserve, and evaluate authentic human stories.'],
 audiences:['Audience Intelligence','Understand where relevance and relationship potential are strongest.'],
 narratives:['Narrative Intelligence','See how public meaning changes over time.'],
 advisory:['AI Advisory Board','Deliberate with distinct strategic perspectives.'],
 campaigns:['Campaign Lab','Turn approved decisions into disciplined execution.'],
 learning:['Institutional Learning','Make every decision improve the next one.'],
 graph:['Knowledge Graph','Explore the relationships across KNIP intelligence.'],
 brief:['Executive Brief','Review the evidence, advisory deliberation, and decision record.']
};
function switchView(name){
 views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));
 navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===name));
 title.textContent=pageMeta[name][0]; subtitle.textContent=pageMeta[name][1];
 window.scrollTo({top:0,behavior:'smooth'});
}
navItems.forEach(n=>n.addEventListener('click',()=>switchView(n.dataset.view)));
document.querySelectorAll('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewJump)));
const toast=document.getElementById('toast');
document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{
 toast.textContent=b.dataset.toast; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2200);
}));
document.getElementById('focusToggle').addEventListener('click',e=>{
 document.body.classList.toggle('focus-mode'); e.currentTarget.classList.toggle('active');
 if(document.body.classList.contains('focus-mode')){e.currentTarget.textContent='Exit Focus Mode'}else{e.currentTarget.textContent='◎ Focus Mode'}
});
document.addEventListener('keydown',e=>{
 if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch').focus()}
 if(e.key==='Escape'&&document.body.classList.contains('focus-mode')){document.body.classList.remove('focus-mode');document.getElementById('focusToggle').classList.remove('active');document.getElementById('focusToggle').textContent='◎ Focus Mode'}
});
document.getElementById('globalSearch').addEventListener('keydown',e=>{
 if(e.key==='Enter'){toast.textContent=`Searching KNIP for “${e.target.value}”`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
});


document.querySelectorAll('[data-open-brief]').forEach(button=>button.addEventListener('click',()=>switchView('brief')));
document.querySelectorAll('.decision-btn').forEach(button=>button.addEventListener('click',()=>{
 const decision=button.dataset.decision;
 const note=document.getElementById('decisionNote').value.trim();
 const state=document.getElementById('decisionState');
 state.textContent=`Decision recorded: ${decision}`;
 document.getElementById('view-brief').classList.add('decision-complete');
 document.querySelectorAll('.decision-btn').forEach(b=>{b.disabled=true;b.style.opacity='.55'});
 button.disabled=false;button.style.opacity='1';button.textContent=`✓ ${decision}`;
 toast.textContent=note ? `${decision} — rationale stored in institutional memory` : `${decision} — decision record created`;
 toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800);
}));


// Build 0.5 — mock story intelligence service and repository controller
const storyIntelligence = [
 {id:1,title:'Kenyan Farmers Using Israeli Water Innovation',summary:'Small-scale farmers describe how precision drip irrigation protected harvests during prolonged drought.',theme:'Climate Resilience',location:'Kenya',status:'Ready',date:'2026-07-21',opportunity:96,evidence:92,audience:94,authenticity:95,reviewer:'Shani',audiences:['Moderate Democrats','Sustainability Leaders','Young Professionals'],narratives:['Human impact','Climate resilience','Food security'],risk:'Keep farmers—not the technology provider—at the center to avoid corporate-promotion framing.',sources:['Direct beneficiary interviews','Local agricultural report','Independent NGO confirmation'],timeline:['Discovered · Jul 18','Verified · Jul 20','Ready for decision · Jul 21']},
 {id:2,title:'Emergency Medical Training in Rural Guatemala',summary:'Israeli-trained emergency responders expand life-saving skills in remote communities with limited hospital access.',theme:'Global Health',location:'Guatemala',status:'Review',date:'2026-07-20',opportunity:88,evidence:84,audience:88,authenticity:90,reviewer:'Shani',audiences:['Healthcare Professionals','Hispanic Civic Leaders','Moderate Democrats'],narratives:['Global health','Local capacity','Human partnership'],risk:'Confirm that local partners receive equal attribution and that outcome data is independently supported.',sources:['Program documentation','Local partner statement','Participant testimony'],timeline:['Discovered · Jul 17','Evidence review · Jul 20']},
 {id:3,title:'Arab and Jewish Students Build Robotics Team',summary:'Teenagers from neighboring communities collaborate on engineering challenges and shared civic leadership.',theme:'Shared Society',location:'Northern Israel',status:'Monitor',date:'2026-07-19',opportunity:85,evidence:79,audience:91,authenticity:89,reviewer:'Ruby',audiences:['Young Progressive Jews','Educators','Gen Z'],narratives:['Shared society','Education','Youth leadership'],risk:'Avoid presenting one program as proof that broader social tensions have been resolved.',sources:['School interviews','Competition record','Teacher documentation'],timeline:['Discovered · Jul 16','Monitoring · Jul 19']},
 {id:4,title:'Desalination Partnership Supports Coastal City',summary:'A municipal partnership uses Israeli water-management knowledge to strengthen drought resilience.',theme:'Water Security',location:'United States',status:'Archived',date:'2026-07-18',opportunity:73,evidence:86,audience:86,authenticity:76,reviewer:'Amit',audiences:['Municipal Leaders','Climate Professionals'],narratives:['Water security','Local government','Infrastructure'],risk:'The institutional story lacks a strong beneficiary voice; retain for research and trend analysis.',sources:['Municipal minutes','Engineering report','Partner announcement'],timeline:['Discovered · Jul 12','Archived for research · Jul 18']},
 {id:5,title:'Bedouin Agritech Cooperative Expands Desert Harvests',summary:'A locally led cooperative combines traditional knowledge with Israeli agritech to improve income and crop stability.',theme:'Food Security',location:'Negev',status:'Ready',date:'2026-07-17',opportunity:91,evidence:89,audience:90,authenticity:96,reviewer:'Ruby',audiences:['Sustainability Leaders','Hispanic Entrepreneurs','Progressive Christians'],narratives:['Local agency','Food security','Inclusive innovation'],risk:'Obtain explicit consent from cooperative members before public amplification.',sources:['Cooperative interviews','Regional data','Academic field study'],timeline:['Discovered · Jul 11','Verified · Jul 16','Ready · Jul 17']},
 {id:6,title:'Trauma Support Exchange Helps Ukrainian Clinicians',summary:'Mental-health practitioners share practical trauma-care methods with clinicians supporting displaced families.',theme:'Global Health',location:'Ukraine',status:'Review',date:'2026-07-16',opportunity:87,evidence:82,audience:84,authenticity:93,reviewer:'Shani',audiences:['Mental Health Professionals','Humanitarian Networks','Young Professionals'],narratives:['Mutual learning','Trauma care','Civil society'],risk:'Protect patient privacy and avoid implying a one-directional transfer of expertise.',sources:['Clinician testimony','Training curriculum','Partner organization record'],timeline:['Discovered · Jul 10','Privacy review · Jul 16']}
];
let selectedStoryId=null, storyListMode=false;
const storyGrid=document.getElementById('storyGrid');
function renderStories(){
 if(!storyGrid)return;
 const q=(document.getElementById('storySearch').value||'').toLowerCase();
 const status=document.getElementById('storyStatus').value, theme=document.getElementById('storyTheme').value, sort=document.getElementById('storySort').value;
 let rows=storyIntelligence.filter(s=>(status==='all'||s.status===status)&&(theme==='all'||s.theme===theme)&&[s.title,s.summary,s.location,s.theme,...s.audiences,...s.narratives].join(' ').toLowerCase().includes(q));
 rows.sort((a,b)=>sort==='newest'?b.date.localeCompare(a.date):sort==='evidence'?b.evidence-a.evidence:b.opportunity-a.opportunity);
 storyGrid.innerHTML=rows.map(s=>`<article class="story-card ${selectedStoryId===s.id?'selected':''}" data-story-id="${s.id}"><div><div class="story-card-head"><span class="eyebrow">${s.location} · ${s.theme}</span><em class="story-status ${s.status}">${s.status}</em></div><h3>${s.title}</h3><p>${s.summary}</p><div class="story-meta">${s.audiences.slice(0,2).map(a=>`<span>${a}</span>`).join('')}<span>Reviewer: ${s.reviewer}</span></div></div><div class="story-scores"><div><strong>${s.opportunity}</strong><small>Opportunity</small></div><div><strong>${s.evidence}</strong><small>Evidence</small></div><div><strong>${s.audience}</strong><small>Audience</small></div></div></article>`).join('');
 document.getElementById('storyEmpty').hidden=rows.length>0;
 storyGrid.querySelectorAll('.story-card').forEach(c=>c.addEventListener('click',()=>openStory(Number(c.dataset.storyId))));
}
function openStory(id){selectedStoryId=id;const s=storyIntelligence.find(x=>x.id===id);renderStories();const d=document.getElementById('storyDetail');d.innerHTML=`<div class="detail-top"><div class="detail-topline"><span class="eyebrow">INTELLIGENCE OBJECT #KNIP-${String(s.id).padStart(4,'0')}</span><em class="story-status ${s.status}">${s.status}</em></div><h3>${s.title}</h3><p>${s.summary}</p></div><div class="detail-body"><section class="detail-section"><div class="detail-score-row"><div><strong>${s.opportunity}</strong><small>Opportunity</small></div><div><strong>${s.authenticity}</strong><small>Authenticity</small></div><div><strong>${s.evidence}</strong><small>Evidence</small></div></div></section><section class="detail-section"><h4>Evidence record</h4><div class="evidence-mini">${s.sources.map(x=>`<div><span>${x}</span><b>Verified</b></div>`).join('')}</div></section><section class="detail-section"><h4>Recommended audiences</h4><div class="audience-mini">${s.audiences.map((x,i)=>`<div><span>${i+1}. ${x}</span><b>${Math.max(70,s.audience-i*4)}%</b></div>`).join('')}</div></section><section class="detail-section"><h4>Risk & sensitivity</h4><div class="risk-box">${s.risk}</div></section><section class="detail-section"><h4>Workflow history</h4><div class="timeline-mini">${s.timeline.map(x=>`<div><span>${x}</span><b>✓</b></div>`).join('')}</div></section><section class="detail-section detail-actions"><button class="btn approve" data-view-jump="brief">Open Executive Brief</button><button class="btn warm" data-story-action="advance">Advance Status</button><button class="btn ghost" data-story-action="archive">Archive</button></section><div class="archive-note">All records remain searchable for institutional learning and academic research, including stories not selected for campaigns.</div></div>`;
 d.querySelector('[data-view-jump]').addEventListener('click',()=>switchView('brief'));
 d.querySelectorAll('[data-story-action]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.storyAction==='archive'){s.status='Archived';toast.textContent='Story preserved in the academic archive';}else{s.status=s.status==='Monitor'?'Review':'Ready';toast.textContent=`Story advanced to ${s.status}`;}toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);openStory(s.id);}));
}
['storySearch','storyStatus','storyTheme','storySort'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='storySearch'?'input':'change',renderStories)});
const viewToggle=document.getElementById('toggleStoryView');if(viewToggle)viewToggle.addEventListener('click',()=>{storyListMode=!storyListMode;storyGrid.classList.toggle('list-mode',storyListMode);viewToggle.textContent=storyListMode?'▦ Grid View':'☷ List View'});
renderStories();


// Build 0.6 — mock multi-agent advisory service
const advisoryDockets={
 water:{question:'Should Kerem amplify the Kenyan farmers story now?',context:'Climate resilience · Moderate Democrats · 72-hour opportunity window',readiness:96,recommendation:'APPROVE WITH MODIFICATION',strength:84,confidence:89,vote:'4–1',title:'Approve with one modification',synthesis:'Use the beneficiaries as the protagonists, cite the independent evidence record, and monitor discussion for twelve hours before paid amplification begins.'},
 medical:{question:'Should Kerem advance the Guatemala medical-training story?',context:'Global health · Hispanic civic leaders · Evidence review',readiness:84,recommendation:'CONTINUE EVIDENCE REVIEW',strength:72,confidence:81,vote:'3–2',title:'Proceed conditionally',synthesis:'Secure independent outcome data and equal attribution for local partners before moving to an executive approval decision.'},
 robotics:{question:'Is the shared robotics story ready for amplification?',context:'Shared society · Gen Z · Monitoring phase',readiness:79,recommendation:'MONITOR',strength:68,confidence:78,vote:'2–3',title:'Monitor before amplification',synthesis:'The audience relevance is strong, but additional testimony and safeguards against overclaiming are required.'}
};
const advisors=[
 {key:'ruby',initial:'R',name:'Ruby',role:'Chief Strategy Officer',confidence:94,position:'Approve',text:'The story builds relevance through a practical climate solution and a human protagonist. It fits the soft-middle strategy.',evidence:'Audience match 94%; narrative momentum is strengthening; opportunity window is time-sensitive.'},
 {key:'shani',initial:'S',name:'Shani',role:'Chief Knowledge Officer',confidence:92,position:'Approve',text:'The evidence record is strong and sufficiently triangulated. Attribution and beneficiary testimony are clear.',evidence:'Direct interviews; local agricultural reporting; independent NGO confirmation.'},
 {key:'amit',initial:'A',name:'Amit',role:'Chief Operations Officer',confidence:88,position:'Approve',text:'The campaign can be produced within five business days using current capacity and partner relationships.',evidence:'Production team available; partner review path identified; budget within approved range.'},
 {key:'cta',initial:'C',name:'CTA',role:'Technology Architect',confidence:82,position:'Monitor',text:'Digital signals are favorable, but a twelve-hour validation window would reduce timing and amplification risk.',evidence:'Rising search interest; incomplete social-sentiment sample; no technical blockers.'},
 {key:'devil',initial:'D',name:"Devil's Advocate",role:'Risk Perspective',confidence:87,position:'Modify',text:'The principal vulnerability is corporate-promotion framing. The campaign must make the farmers—not the vendor—the heroes.',evidence:'Technology-first framing has underperformed; beneficiary-led stories have stronger trust outcomes.'}
];
function renderAdvisors(pulse=false){
 const grid=document.getElementById('advisorGrid'); if(!grid)return;
 grid.innerHTML=advisors.map(a=>`<article class="advisor-agent ${a.key} ${pulse?'pulse':''}"><header><span>${a.initial}</span><div><b>${a.name}</b><small>${a.role}</small></div><em>${a.confidence}%</em></header><p>${a.text}</p><details><summary>View reasoning & evidence</summary><div><b>Position: ${a.position}</b><br>${a.evidence}</div></details></article>`).join('');
}
function loadDocket(key){
 const d=advisoryDockets[key];
 document.getElementById('docketQuestion').textContent=d.question;document.getElementById('docketContext').textContent=d.context;document.getElementById('docketReadiness').textContent=`Readiness ${d.readiness}%`;document.getElementById('boardRecommendation').textContent=d.recommendation;document.getElementById('consensusStrength').textContent=`${d.strength}%`;document.getElementById('averageConfidence').textContent=`${d.confidence}%`;document.getElementById('voteCount').textContent=d.vote;document.getElementById('synthesisTitle').textContent=d.title;document.getElementById('synthesisText').textContent=d.synthesis;document.querySelectorAll('.docket-item').forEach(x=>x.classList.toggle('selected',x.dataset.docket===key));renderAdvisors(true);
}
document.querySelectorAll('.docket-item').forEach(x=>x.addEventListener('click',()=>loadDocket(x.dataset.docket)));
const run=document.getElementById('runDeliberation');if(run)run.addEventListener('click',()=>{run.disabled=true;run.textContent='Deliberating…';document.getElementById('boardResponse').hidden=true;setTimeout(()=>{renderAdvisors(true);run.disabled=false;run.textContent='Run New Deliberation';toast.textContent='Five advisor perspectives refreshed';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)},900)});
const ask=document.getElementById('askBoard');if(ask)ask.addEventListener('click',()=>{const q=document.getElementById('boardQuestion').value.trim();const r=document.getElementById('boardResponse');r.hidden=false;r.innerHTML=`<b>Board synthesis</b>${q?`For “${q}”, `:''}the board recommends preserving the human-centered framing, maintaining source transparency, and recording the dissenting technical view in the decision audit trail.`});
const challenge=document.getElementById('challengeBoard');if(challenge)challenge.addEventListener('click',()=>{const r=document.getElementById('boardResponse');r.hidden=false;r.innerHTML='<b>Challenge result</b>The recommendation remains approve-with-modification. The strongest reason to delay is incomplete short-term signal validation; the strongest reason to act is the 72-hour opportunity window.'});
const compare=document.getElementById('comparePositions');if(compare)compare.addEventListener('click',()=>{const r=document.getElementById('boardResponse');r.hidden=false;r.innerHTML='<b>Position comparison</b>Ruby prioritizes strategic timing; Shani prioritizes evidence integrity; Amit prioritizes executable readiness; CTA prioritizes signal validation; the Devil’s Advocate prioritizes reputational safeguards.'});
renderAdvisors();

// Build 0.7 — Audience Intelligence service and decision workspace
const audienceProfiles=[
 {id:'moderate-democrats',name:'Moderate Democrats',region:'United States',priority:'High',summary:'Pragmatic center-left voters motivated by democracy, fairness, competence, climate, healthcare, and visible human outcomes.',health:64,opportunity:91,persuadability:78,readiness:88,confidence:89,trend:'Improving',relationshipGap:'High',values:['Democracy','Human dignity','Fairness','Science','Climate action','Community'],strengths:[['Innovation',91],['Healthcare',86],['Climate solutions',84],['Academic cooperation',78]],weaknesses:[['Government leadership',39],['Human-rights perception',44],['Conflict framing',48],['Settlements',51]],use:['partnership','shared future','community','practical solutions','human impact','democratic resilience'],avoid:['propaganda','political slogans','zero-sum language','victory framing','conflict-first opening'],messengers:[['Physicians',96],['Scientists',94],['Teachers',90],['Civil-society leaders',88]],stories:[['Kenyan farmers · water resilience',96],['Rural medical training',93],['Trauma-care exchange',89],['Shared robotics team',85]],objections:[['Humanitarian impact','Lead with independently verified beneficiary outcomes and acknowledge complexity.'],['Democracy','Show civil society, institutions, and pluralistic voices rather than government claims.'],['Settlements','Do not evade the concern; keep the opening focused on the specific human story.']],channels:['Podcasts','Local media','Community newsletters','University events','Short documentary video'],formats:['Beneficiary testimony','Expert interview','Field reporting','Data-supported human story'],journey:'Interested',objective:'Increase long-term trust by connecting Israeli civil-society impact to shared democratic and humanitarian values.',recommendation:'Lead with beneficiaries, not Israeli achievement. Use independent evidence and trusted professional messengers. Avoid geopolitical framing in the opening message.',evolution:[['2018',81],['2020',76],['2022',70],['2024',61],['Today',64]]},
 {id:'hispanic-evangelicals',name:'Young Hispanic Evangelicals',region:'United States',priority:'High',summary:'Faith-oriented younger adults whose views are shaped by family, community service, entrepreneurship, and trusted congregational networks.',health:78,opportunity:88,persuadability:72,readiness:81,confidence:82,trend:'Stable',relationshipGap:'Medium',values:['Faith','Family','Community','Service','Opportunity','Hope'],strengths:[['Biblical connection',88],['Innovation',80],['Humanitarian aid',79],['Entrepreneurship',77]],weaknesses:[['Political polarization',48],['Limited direct exposure',54],['Conflict fatigue',56],['Institutional distrust',59]],use:['service','family','hope','community partnership','dignity','opportunity'],avoid:['partisan cues','elite language','lecturing','fear-based appeals'],messengers:[['Local pastors',96],['Community entrepreneurs',91],['Healthcare workers',88],['Young faith leaders',87]],stories:[['Guatemala medical training',95],['Bedouin agritech cooperative',89],['Family resilience stories',86],['Water access partnerships',84]],objections:[['Political conflict','Keep party politics out of the frame and emphasize service.'],['Distance from Israel','Use relatable local partners and Spanish-language testimony.'],['Authenticity','Prioritize ordinary people and congregationally trusted messengers.']],channels:['Church networks','Spanish-language podcasts','WhatsApp communities','Local radio','Short video'],formats:['Personal testimony','Pastor conversation','Community event','Family-centered video'],journey:'Aware',objective:'Build relevance through faith-compatible stories of service, family resilience, and local partnership.',recommendation:'Use trusted community and faith messengers. Lead with service and family outcomes, not ideology or political alignment.',evolution:[['2018',82],['2020',81],['2022',80],['2024',77],['Today',78]]},
 {id:'genz-jewish',name:'Gen Z Jewish Students',region:'North America',priority:'High',summary:'Young Jews balancing identity, peer culture, justice concerns, campus dynamics, and a desire for honest, pluralistic engagement.',health:52,opportunity:90,persuadability:76,readiness:73,confidence:78,trend:'Vulnerable',relationshipGap:'Very High',values:['Belonging','Justice','Pluralism','Authenticity','Identity','Agency'],strengths:[['Culture and community',82],['Innovation',74],['Pluralistic Judaism',73],['Shared society',71]],weaknesses:[['War and Gaza',31],['Government leadership',34],['Peer environment',38],['Trust in advocacy',40]],use:['honesty','complexity','belonging','shared responsibility','pluralism','agency'],avoid:['loyalty tests','hasbara','dismissal of concerns','institutional talking points'],messengers:[['Peers',97],['Young Israeli civil-society voices',92],['Campus educators',86],['Artists and creators',82]],stories:[['Arab-Jewish robotics team',94],['Pluralistic community stories',91],['Youth volunteer initiatives',88],['Environmental cooperation',84]],objections:[['Moral discomfort','Acknowledge rather than minimize; create space for questions.'],['Distrust of advocacy','Use transparent sourcing and independent voices.'],['Peer pressure','Offer community and language that supports complexity.']],channels:['Instagram','Campus conversations','Podcasts','Small-group events','Creator-led video'],formats:['Peer dialogue','First-person essay','Unscripted interview','Interactive event'],journey:'Aware',objective:'Rebuild trust and belonging through honest, pluralistic, peer-led engagement that permits complexity.',recommendation:'Do not begin by defending policy. Begin with identity, belonging, civil society, and honest acknowledgment of difficult questions.',evolution:[['2018',72],['2020',66],['2022',61],['2024',49],['Today',52]]},
 {id:'healthcare',name:'Healthcare Professionals',region:'United States',priority:'Medium',summary:'Evidence-oriented professionals who respond to measurable outcomes, peer expertise, ethical practice, and cross-border collaboration.',health:86,opportunity:80,persuadability:61,readiness:92,confidence:93,trend:'Strong',relationshipGap:'Low',values:['Evidence','Ethics','Care','Competence','Innovation','Professionalism'],strengths:[['Medical innovation',94],['Emergency medicine',91],['Research collaboration',89],['Trauma care',88]],weaknesses:[['Commercial overclaiming',52],['Political branding',58],['Attribution gaps',61],['Data transparency',66]],use:['patient outcomes','peer-reviewed','clinical collaboration','capacity building','ethics'],avoid:['miracle claims','national boasting','unsupported superlatives','political framing'],messengers:[['Physicians',98],['Clinical researchers',97],['Hospital leaders',91],['Patients with consent',89]],stories:[['Trauma-care exchange',96],['Rural emergency training',94],['Medical-device collaboration',91],['Hospital partnerships',88]],objections:[['Evidence quality','Provide methodology, outcomes, and independent verification.'],['Commercial promotion','Separate public benefit from vendor marketing.'],['Ethics','Make consent, privacy, and local agency explicit.']],channels:['Professional journals','Conferences','LinkedIn','Hospital networks','Webinars'],formats:['Case study','Peer interview','Clinical briefing','Research summary'],journey:'Engaged',objective:'Deepen professional collaboration and convert strong sector credibility into broader relationship value.',recommendation:'Use clinician-to-clinician communication with rigorous evidence. This audience is campaign-ready but intolerant of overclaiming.',evolution:[['2018',82],['2020',84],['2022',87],['2024',85],['Today',86]]},
 {id:'climate-leaders',name:'Young Sustainability Leaders',region:'United States',priority:'High',summary:'Climate-focused professionals and organizers seeking scalable solutions, justice-oriented implementation, and credible local impact.',health:68,opportunity:89,persuadability:80,readiness:86,confidence:86,trend:'Improving',relationshipGap:'High',values:['Climate action','Equity','Local agency','Science','Scale','Accountability'],strengths:[['Water technology',94],['Desert agriculture',90],['Climate adaptation',88],['Research',83]],weaknesses:[['Greenwashing concern',43],['Political associations',49],['Equity questions',54],['Corporate framing',56]],use:['climate resilience','local ownership','adaptation','measurable impact','shared solutions'],avoid:['tech solutionism','greenwashing','Israel-first credit','ignoring local knowledge'],messengers:[['Local farmers',97],['Climate scientists',94],['Municipal leaders',88],['Environmental NGOs',87]],stories:[['Kenyan farmers',98],['Bedouin agritech cooperative',94],['Coastal water partnership',88],['Desert research collaboration',86]],objections:[['Greenwashing','Show independent outcomes and limitations.'],['Local agency','Make local partners the protagonists and co-designers.'],['Justice','Explain who benefits and how access is distributed.']],channels:['LinkedIn','Climate newsletters','Conferences','Documentary video','Local media'],formats:['Field story','Data visualization','Expert panel','Partner testimony'],journey:'Interested',objective:'Establish Israel as a useful, accountable partner in climate resilience without technology-first triumphalism.',recommendation:'Lead with local agency and measurable resilience. Technology is supporting evidence, not the hero.',evolution:[['2018',65],['2020',66],['2022',67],['2024',65],['Today',68]]},
 {id:'african-american-faith',name:'African-American Faith Leaders',region:'United States',priority:'Medium',summary:'Community-rooted leaders attentive to justice, historical memory, family wellbeing, local service, and moral credibility.',health:57,opportunity:82,persuadability:69,readiness:67,confidence:74,trend:'Uncertain',relationshipGap:'High',values:['Justice','Faith','Community','Dignity','Historical memory','Service'],strengths:[['Faith connection',75],['Medical cooperation',72],['Civil-rights dialogue',68],['Community service',67]],weaknesses:[['Palestinian solidarity',38],['Justice framing',41],['Limited relationships',49],['Political distrust',51]],use:['mutual dignity','listening','community partnership','faith in action','shared struggle'],avoid:['comparison of suffering','transactional outreach','partisan messaging','defensiveness'],messengers:[['Pastors with relationships',96],['Community organizers',89],['Healthcare leaders',84],['Civil-rights educators',82]],stories:[['Community health partnerships',90],['Faith-based service exchange',86],['Emergency response training',82],['Shared-society initiatives',78]],objections:[['Justice and Palestinians','Listen first and acknowledge the moral concern directly.'],['Transactional outreach','Invest in long-term relationships before asking for public support.'],['Historical analogy','Avoid competitive victimhood or simplistic comparisons.']],channels:['Church gatherings','Community radio','Small-group dialogue','Local newspapers','Pastoral networks'],formats:['Listening session','Clergy dialogue','Community partnership story','Long-form interview'],journey:'Aware',objective:'Develop durable relationships based on listening, shared service, and moral seriousness rather than immediate persuasion.',recommendation:'This is a relationship-building audience, not a rapid campaign target. Begin with listening and credible local partnerships.',evolution:[['2018',63],['2020',61],['2022',59],['2024',56],['Today',57]]}
];
let selectedAudienceId='moderate-democrats', audienceTab='intelligence';
const scoreRow=(label,value,weak=false)=>`<div class="strength-row ${weak?'weak':''}"><span>${label}</span><span class="track"><i style="width:${value}%"></i></span><b>${value}</b></div>`;
function renderAudienceList(){
 const list=document.getElementById('audienceList'); if(!list)return;
 const q=(document.getElementById('audienceSearch')?.value||'').toLowerCase(), region=document.getElementById('audienceRegion')?.value||'all', priority=document.getElementById('audiencePriority')?.value||'all', sort=document.getElementById('audienceSort')?.value||'priority';
 let rows=audienceProfiles.filter(a=>(region==='all'||a.region===region)&&(priority==='all'||a.priority===priority)&&[a.name,a.summary,...a.values,...a.use,...a.messengers.flat()].join(' ').toLowerCase().includes(q));
 rows.sort((a,b)=>sort==='opportunity'?b.opportunity-a.opportunity:sort==='health'?b.health-a.health:(a.priority===b.priority?b.opportunity-a.opportunity:a.priority==='High'?-1:1));
 document.getElementById('audienceCount').textContent=`${rows.length} profiles`;
 list.innerHTML=rows.map(a=>`<button class="audience-list-item ${a.id===selectedAudienceId?'selected':''}" data-audience-id="${a.id}"><b>${a.name}</b><small>${a.region} · ${a.trend}</small><em>${a.opportunity}</em><div class="mini-score"><span>Health ${a.health}</span><span>Ready ${a.readiness}</span></div></button>`).join('');
 list.querySelectorAll('[data-audience-id]').forEach(x=>x.addEventListener('click',()=>{selectedAudienceId=x.dataset.audienceId;audienceTab='intelligence';renderAudienceList();renderAudienceDossier()}));
}
const metricDefinitions={
 health:{label:'Relationship Health',description:'Composite estimate of the audience’s current relationship with Israel.',weights:[['Public opinion research',22],['Digital conversation',18],['Focus groups & interviews',15],['Campaign outcomes',14],['Academic research',12],['News environment',10],['Partner observations',9]]},
 opportunity:{label:'Strategic Opportunity',description:'Estimated value of sustained engagement relative to mission fit and available narrative assets.',weights:[['Audience relevance',25],['Persuadability',20],['Story availability',18],['Messenger access',15],['Strategic importance',12],['Competitive narrative gap',10]]},
 persuadability:{label:'Persuadability',description:'Estimated openness to evidence, trusted messengers, and repeated relationship-building.',weights:[['Openness to new information',25],['Strength of fixed attitudes',20],['Trusted messenger availability',20],['Historical responsiveness',15],['Issue salience',10],['Message saturation',10]]},
 readiness:{label:'Decision Readiness',description:'Whether KNIP has enough current evidence and operational capacity to recommend action.',weights:[['Evidence quality',25],['Source diversity',15],['Audience research',20],['Historical performance',15],['AI board consensus',15],['Human review',10]]},
 trend:{label:'Current Trend',description:'Direction of change inferred from a time series of relationship signals.',weights:[['Polling movement',30],['Digital sentiment movement',20],['Media narrative movement',15],['Campaign response',20],['Qualitative research',15]]}
};
function metricValue(a,key){return key==='trend'?a.trend:a[key]}
function simulatedLineage(a,key){
 const d=metricDefinitions[key];
 return {title:d.label,value:metricValue(a,key),confidence:a.confidence,freshness:'Simulated · review build',coverage:a.region,model:'KNIP Demo Scoring Model 0.8',description:d.description,weights:d.weights,assumptions:['Representative placeholder data is used for interface validation.','No live polling, platform, media, or campaign feeds are connected.','Production scores will require source normalization, recency weighting, and analyst review.'],sources:['Public polling connector (planned)','Digital conversation connector (planned)','Media intelligence connector (planned)','Campaign analytics connector (planned)','Human research and focus-group records (planned)']}
}
function openAudit(a,key='health'){
 const x=simulatedLineage(a,key), modal=document.getElementById('auditModal'), host=document.getElementById('auditContent');
 document.getElementById('auditTitle').textContent=`${a.name} · ${x.title}`;
 host.innerHTML=`<div class="audit-status"><span>SIMULATED DATA</span><b>${x.value}</b><small>${x.title}</small></div><p class="audit-description">${x.description}</p><div class="audit-meta"><div><small>Confidence</small><b>${x.confidence}%</b></div><div><small>Freshness</small><b>${x.freshness}</b></div><div><small>Coverage</small><b>${x.coverage}</b></div><div><small>Model</small><b>${x.model}</b></div></div><section class="audit-section"><h3>Calculation factors</h3>${x.weights.map(w=>`<div class="weight-row"><span>${w[0]}</span><div><i style="width:${w[1]*3}%"></i></div><b>${w[1]}%</b></div>`).join('')}</section><section class="audit-section"><h3>Data lineage</h3><div class="lineage-flow"><span>Source evidence</span><i>→</i><span>Normalization</span><i>→</i><span>Recency weighting</span><i>→</i><span>Model synthesis</span><i>→</i><span>Human review</span></div><div class="source-plan">${x.sources.map(s=>`<div><span>○</span>${s}</div>`).join('')}</div></section><section class="audit-section"><h3>Assumptions & limitations</h3><ul>${x.assumptions.map(s=>`<li>${s}</li>`).join('')}</ul></section><footer class="audit-footer"><span>KNIP never asks the executive to trust AI. KNIP asks the executive to inspect AI.</span><button class="btn secondary" data-toast="Audit record exported">Export Audit Record</button></footer>`;
 modal.hidden=false; document.body.classList.add('audit-open');
 host.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{toast.textContent=b.dataset.toast;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}));
}
function closeAudit(){document.getElementById('auditModal').hidden=true;document.body.classList.remove('audit-open')}
document.querySelectorAll('[data-close-audit]').forEach(x=>x.addEventListener('click',closeAudit));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('auditModal').hidden)closeAudit()});

function renderAudienceDossier(){
 const a=audienceProfiles.find(x=>x.id===selectedAudienceId), host=document.getElementById('audienceDossier'); if(!host)return;
 host.innerHTML=`<div class="audience-hero"><div class="audience-hero-top"><div><span class="eyebrow" style="color:#bcd8ff">AUDIENCE INTELLIGENCE OBJECT</span><h2>${a.name}</h2><p>${a.summary}</p></div><span class="audience-priority-badge">${a.priority.toUpperCase()} PRIORITY</span></div><div class="audience-scoreboard"><button data-audit-metric="health"><strong>${a.health}</strong><small>Relationship Health</small><em>Why?</em></button><button data-audit-metric="opportunity"><strong>${a.opportunity}</strong><small>Strategic Opportunity</small><em>Why?</em></button><button data-audit-metric="persuadability"><strong>${a.persuadability}</strong><small>Persuadability</small><em>Why?</em></button><button data-audit-metric="readiness"><strong>${a.readiness}</strong><small>Decision Readiness</small><em>Why?</em></button><button data-audit-metric="trend"><strong class="trend-up">${a.trend}</strong><small>Current Trend</small><em>Why?</em></button></div></div>
 <div class="audience-tabs"><button class="audience-tab ${audienceTab==='intelligence'?'active':''}" data-audience-tab="intelligence">Intelligence View</button><button class="audience-tab ${audienceTab==='strategy'?'active':''}" data-audience-tab="strategy">Strategy View</button><button class="audience-tab ${audienceTab==='playbook'?'active':''}" data-audience-tab="playbook">Audience Playbook</button><button class="audience-tab ${audienceTab==='evolution'?'active':''}" data-audience-tab="evolution">Evolution & Learning</button><button class="audience-tab ${audienceTab==='audit'?'active':''}" data-audience-tab="audit">Explainability & Audit</button></div>
 <div class="audience-tab-panel ${audienceTab==='intelligence'?'active':''}" data-tab-panel="intelligence"><div class="dossier-grid"><article class="intel-card"><h3>Audience DNA</h3><div class="tag-cloud">${a.values.map(v=>`<span>${v}</span>`).join('')}</div></article><article class="intel-card"><h3>Relationship Assessment</h3><p style="font-size:11px;color:var(--muted);line-height:1.55">Relationship gap: <b>${a.relationshipGap}</b><br>Research confidence: <b>${a.confidence}%</b><br>Trajectory: <b>${a.trend}</b></p></article><article class="intel-card"><h3>Israel's Current Strengths</h3>${a.strengths.map(x=>scoreRow(x[0],x[1])).join('')}</article><article class="intel-card"><h3>Current Weaknesses</h3>${a.weaknesses.map(x=>scoreRow(x[0],x[1],true)).join('')}</article><article class="intel-card"><h3>Opinion Drivers</h3><div class="tag-cloud">${[...a.channels.slice(0,3),'Peers','Trusted institutions'].map(v=>`<span>${v}</span>`).join('')}</div></article><article class="intel-card"><h3>Audience Journey</h3><div class="journey">${['Unaware','Aware','Interested','Engaged','Advocate','Partner'].map((v,i)=>`${i?'<i>→</i>':''}<span class="${v===a.journey?'current':''}">${v}</span>`).join('')}</div></article></div></div>
 <div class="audience-tab-panel ${audienceTab==='strategy'?'active':''}" data-tab-panel="strategy"><div class="dossier-grid"><article class="intel-card wide strategy-callout"><h3>Executive Recommendation</h3><p><b>Objective:</b> ${a.objective}</p><p>${a.recommendation}</p><div class="audience-actions"><button class="btn approve" data-toast="Audience strategy moved to Mission Planner">Create Mission</button><button class="btn secondary" data-toast="Audience brief generated">Generate Executive Brief</button><button class="btn ghost" data-toast="AI Advisory Board opened for this audience">Ask Advisory Board</button></div></article><article class="intel-card"><h3>Language That Resonates</h3><div class="tag-cloud good">${a.use.map(v=>`<span>${v}</span>`).join('')}</div></article><article class="intel-card"><h3>Language & Framing to Avoid</h3><div class="tag-cloud avoid">${a.avoid.map(v=>`<span>${v}</span>`).join('')}</div></article><article class="intel-card"><h3>Trusted Messengers</h3><div class="messenger-list">${a.messengers.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></article><article class="intel-card"><h3>Best Story Matches</h3><div class="story-match-list">${a.stories.map(x=>`<div><span>${x[0]}</span><b>${x[1]}%</b></div>`).join('')}</div></article><article class="intel-card wide"><h3>Objection Intelligence</h3><div class="objection-list">${a.objections.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div></article><article class="intel-card"><h3>Preferred Channels</h3><div class="tag-cloud">${a.channels.map(v=>`<span>${v}</span>`).join('')}</div></article><article class="intel-card"><h3>Preferred Formats</h3><div class="tag-cloud">${a.formats.map(v=>`<span>${v}</span>`).join('')}</div></article></div></div>
 <div class="audience-tab-panel ${audienceTab==='playbook'?'active':''}" data-tab-panel="playbook"><div class="playbook-section"><h4>1. Strategic Objective</h4><p>${a.objective}</p></div><div class="playbook-section"><h4>2. Lead With</h4><p>${a.use.join(' · ')}</p></div><div class="playbook-section"><h4>3. Do Not Lead With</h4><p>${a.avoid.join(' · ')}</p></div><div class="playbook-section"><h4>4. Messenger Portfolio</h4><p>${a.messengers.map(x=>x[0]).join(' · ')}</p></div><div class="playbook-section"><h4>5. Story Portfolio</h4><p>${a.stories.map(x=>x[0]).join(' · ')}</p></div><div class="playbook-section"><h4>6. Success Measures</h4><p>Relationship health · trust · story completion · repeat exposure · credible third-party engagement · movement to the next audience-journey stage.</p></div><div class="audience-actions"><button class="btn secondary" data-toast="Living audience playbook exported">Export Playbook</button><button class="btn ghost" data-toast="Playbook review assigned to Shani">Assign Review</button></div></div>
 <div class="audience-tab-panel ${audienceTab==='evolution'?'active':''}" data-tab-panel="evolution"><div class="dossier-grid"><article class="intel-card wide"><h3>Relationship Evolution</h3><div class="evolution-chart">${a.evolution.map(x=>`<div><i style="height:${x[1]}%"></i><b>${x[1]}</b><small>${x[0]}</small></div>`).join('')}</div></article><article class="intel-card"><h3>What Has Worked</h3><div class="tag-cloud good"><span>Human-centered framing</span><span>Independent sources</span><span>Trusted messengers</span><span>Local partnerships</span></div></article><article class="intel-card"><h3>What Has Underperformed</h3><div class="tag-cloud avoid"><span>Technology-first claims</span><span>Political slogans</span><span>One-off outreach</span><span>Overclaiming</span></div></article><article class="intel-card wide"><h3>Institutional Learning Note</h3><p style="font-size:11px;line-height:1.6;color:var(--muted)">Future campaigns should update this profile with outcome data, messenger effectiveness, language performance, and observed changes in relationship health. The profile is a living intelligence object, not a static demographic description.</p></article></div></div><div class="audience-tab-panel ${audienceTab==='audit'?'active':''}" data-tab-panel="audit"><div class="dossier-grid"><article class="intel-card wide audit-principle"><span>CORE PRINCIPLE</span><h3>No mystery scores.</h3><p>Every score, trend, forecast, and recommendation must disclose its factors, weights, sources, freshness, confidence, assumptions, model version, and human interventions.</p></article>${['health','opportunity','persuadability','readiness','trend'].map(k=>{const d=metricDefinitions[k];return `<button class="metric-audit-card" data-audit-metric="${k}"><span>${k==='trend'?a.trend:a[k]}</span><div><h3>${d.label}</h3><p>${d.description}</p><small>Inspect calculation →</small></div></button>`}).join('')}<article class="intel-card wide"><h3>Production Data Pipeline</h3><div class="lineage-flow permanent"><span>Polling & research</span><i>→</i><span>Media & digital signals</span><i>→</i><span>Campaign outcomes</span><i>→</i><span>Normalization & weighting</span><i>→</i><span>AI synthesis</span><i>→</i><span>Human approval</span></div><p class="audit-note">This review build demonstrates the workflow only. Live source connectors, source licensing, methodology governance, and analyst validation will be implemented in the production release.</p></article></div></div>`;
 host.querySelectorAll('[data-audience-tab]').forEach(b=>b.addEventListener('click',()=>{audienceTab=b.dataset.audienceTab;renderAudienceDossier()}));
 host.querySelectorAll('[data-audit-metric]').forEach(b=>b.addEventListener('click',()=>openAudit(a,b.dataset.auditMetric)));
 host.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{toast.textContent=b.dataset.toast;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}));
}
function renderComparison(){
 const host=document.getElementById('comparisonTable'); if(!host)return;
 host.innerHTML=`<table><thead><tr><th>Audience</th><th>Relationship Health</th><th>Opportunity</th><th>Persuadability</th><th>Readiness</th><th>Trend</th><th>Priority</th></tr></thead><tbody>${audienceProfiles.map(a=>`<tr><td><strong>${a.name}</strong></td><td>${a.health}</td><td class="${a.opportunity===Math.max(...audienceProfiles.map(x=>x.opportunity))?'best':''}">${a.opportunity}</td><td>${a.persuadability}</td><td>${a.readiness}</td><td>${a.trend}</td><td>${a.priority}</td></tr>`).join('')}</tbody></table>`;
}
['audienceSearch','audienceRegion','audiencePriority','audienceSort'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='audienceSearch'?'input':'change',renderAudienceList)});
const compareAudiences=document.getElementById('compareAudiences'); if(compareAudiences)compareAudiences.addEventListener('click',()=>{const c=document.getElementById('audienceComparison');c.hidden=false;renderComparison();c.scrollIntoView({behavior:'smooth'})});
const closeComparison=document.getElementById('closeComparison'); if(closeComparison)closeComparison.addEventListener('click',()=>document.getElementById('audienceComparison').hidden=true);
renderAudienceList();renderAudienceDossier();

const openMethodology=document.getElementById('openMethodology');if(openMethodology)openMethodology.addEventListener('click',()=>openAudit(audienceProfiles.find(x=>x.id===selectedAudienceId),'health'));

// Build 0.9 — unified platform architecture demonstration
pageMeta.platform=['Platform Architecture','Inspect KNIP’s entities, evidence, sources, connectors, pipeline, and governance.'];
const platformEntities={
 Mission:{description:'The strategic objective that organizes audience, narrative, resource, execution, and measurement decisions.',fields:['id','objective','owner','time horizon','budget','status','version history']},
 Audience:{description:'A living intelligence profile describing a demographic’s relationship, values, concerns, persuadability, and engagement strategy.',fields:['id','segment definition','health','opportunity','research evidence','playbook','trend']},
 Story:{description:'A preserved intelligence object representing an authentic human story whether or not it is selected for a campaign.',fields:['id','summary','beneficiaries','sources','evidence','risks','status']},
 Narrative:{description:'A strategic meaning structure supported by stories, messengers, evidence, and measurable audience response.',fields:['id','proposition','momentum','audiences','supporting stories','counter-narratives']},
 Messenger:{description:'A credible voice scored by audience trust, expertise, narrative fit, availability, and prior performance.',fields:['id','identity','expertise','trust by audience','conflicts','performance']},
 Campaign:{description:'The execution object connecting an approved decision to channels, resources, timeline, content, and outcomes.',fields:['id','mission','audience','story portfolio','messengers','channels','metrics']},
 Decision:{description:'The permanent record of options considered, evidence used, AI advice, human rationale, and final disposition.',fields:['id','question','options','recommendation','human decision','rationale','audit trail']},
 Evidence:{description:'A validated supporting record with source lineage, reliability, scope, freshness, restrictions, and relevance.',fields:['id','source','collected date','reliability','confidence','scope','validation']},
 Source:{description:'An origin of evidence independently rated for standards, accuracy, transparency, timeliness, and relevance.',fields:['id','publisher','type','reliability profile','license','connector']},
 Organization:{description:'An institution participating in the narrative ecosystem as partner, source, competitor, funder, or subject.',fields:['id','name','role','geography','relationships','history']},
 Outcome:{description:'Observed results linked to a campaign and measured against mission objectives and prior assumptions.',fields:['id','metrics','baseline','result','confidence','attribution']},
 Learning:{description:'A validated lesson derived from decisions and outcomes that modifies future playbooks and recommendations.',fields:['id','finding','evidence','applicability','rule updates','review status']},
 User:{description:'A human actor with role-based permissions, review authority, decision accountability, and audit identity.',fields:['id','role','permissions','organization','decision authority','activity log']}
};
const entityMap=document.getElementById('entityMap'),entityInspector=document.getElementById('entityInspector');
function inspectEntity(name){if(!entityMap||!entityInspector)return;entityMap.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.entity===name));const e=platformEntities[name];entityInspector.innerHTML=`<h4>${name}</h4><p>${e.description}</p><div class="entity-fields">${e.fields.map(f=>`<span>${f}</span>`).join('')}</div>`}
if(entityMap){entityMap.innerHTML=Object.keys(platformEntities).map(n=>`<button class="entity-chip" data-entity="${n}">${n}</button>`).join('');entityMap.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>inspectEntity(b.dataset.entity)));inspectEntity('Mission')}
const pipelineSteps=['Evidence collection','Evidence validation','Audience analysis','Narrative analysis','AI Advisory Board review','Executive recommendation','Human decision','Campaign execution','Outcome measurement','Institutional learning'];let pipelineStage=0;
function renderPlatformPipeline(){const host=document.getElementById('recommendationPipeline');if(!host)return;host.innerHTML=pipelineSteps.map((s,i)=>`<div class="pipeline-step ${i<pipelineStage?'done':i===pipelineStage?'current':''}"><i>${i<pipelineStage?'✓':i+1}</i><span>${s}</span></div>`).join('');document.getElementById('pipelineStatus').textContent=`Stage ${Math.min(pipelineStage+1,10)} of 10`}
const advancePipeline=document.getElementById('advancePipeline');if(advancePipeline)advancePipeline.addEventListener('click',()=>{pipelineStage=Math.min(9,pipelineStage+1);renderPlatformPipeline();toast.textContent=`Pipeline advanced to ${pipelineSteps[pipelineStage]}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});const resetPipeline=document.getElementById('resetPipeline');if(resetPipeline)resetPipeline.addEventListener('click',()=>{pipelineStage=0;renderPlatformPipeline()});renderPlatformPipeline();
const evidenceRows=[
 {title:'National opinion survey — Democratic voters',source:'Public polling consortium',state:'Validated',confidence:91,freshness:'12 days'},
 {title:'Climate-story campaign completion data',source:'KNIP campaign outcomes',state:'Validated',confidence:88,freshness:'4 days'},
 {title:'Moderate Democrat focus groups',source:'Research partner',state:'Review',confidence:82,freshness:'31 days'},
 {title:'Digital discussion sample',source:'Public social channels',state:'Restricted',confidence:69,freshness:'6 hours'},
 {title:'Healthcare messenger trust study',source:'Academic research',state:'Validated',confidence:86,freshness:'74 days'}
];
function renderEvidenceRegistry(){const host=document.getElementById('evidenceRegistry');if(!host)return;const q=(document.getElementById('evidenceSearch').value||'').toLowerCase(),state=document.getElementById('evidenceValidation').value;const rows=evidenceRows.filter(r=>(state==='all'||r.state===state)&&`${r.title} ${r.source}`.toLowerCase().includes(q));host.innerHTML=rows.map(r=>`<div class="evidence-row"><div><strong>${r.title}</strong><span>${r.source}</span></div><span class="validation-pill ${r.state}">${r.state}</span><span>Confidence ${r.confidence}%</span><span>${r.freshness}</span></div>`).join('')||'<p class="platform-note">No evidence records match this filter.</p>'}
['evidenceSearch','evidenceValidation'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='evidenceSearch'?'input':'change',renderEvidenceRegistry)});renderEvidenceRegistry();
const sourceScores=[['Peer-reviewed research',94,'Strong methods, disclosure, and review standards.'],['Established polling',91,'Transparent sampling and reproducible methodology.'],['Independent local reporting',84,'High contextual relevance with corroboration required.'],['Partner documentation',72,'Useful primary material with incentive and attribution review.'],['Public digital signals',61,'Timely but noisy, incomplete, and vulnerable to manipulation.']];const sourceHost=document.getElementById('sourceReliability');if(sourceHost)sourceHost.innerHTML=sourceScores.map(s=>`<div class="source-score"><header><b>${s[0]}</b><strong>${s[1]}</strong></header><p>${s[2]}</p><span class="bar"><i style="width:${s[1]}%"></i></span></div>`).join('');
const connectors=[['Polling','Surveys and trend series'],['News','Licensed media feeds'],['Academic','Research databases'],['Social','Public digital signals'],['Campaign Analytics','Owned outcome data'],['CRM','Partners and relationships'],['Document Library','Internal evidence'],['Vector Search','Semantic retrieval']];const connectorHost=document.getElementById('connectorGrid');if(connectorHost){connectorHost.innerHTML=connectors.map((c,i)=>`<article class="connector-card"><header><b>${c[0]}</b><span class="connector-state">NOT CONNECTED</span></header><p>${c[1]}</p><button data-connector="${i}">Simulate connection</button></article>`).join('');connectorHost.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const card=b.closest('.connector-card');card.classList.toggle('enabled');const on=card.classList.contains('enabled');card.querySelector('.connector-state').textContent=on?'SIMULATED':'NOT CONNECTED';b.textContent=on?'Disconnect simulation':'Simulate connection'}))}
const chainDescriptions={Mission:'Defines why the organization is acting and the measurable change sought.',Audience:'Identifies whose relationship or behavior the mission intends to influence.',Narrative:'Defines the strategic meaning that should become more credible or relevant.',Story:'Provides authentic human evidence capable of carrying the narrative.',Messenger:'Determines who can credibly tell the story to the selected audience.',Campaign:'Turns the approved strategic choice into coordinated execution.',Outcome:'Records what changed, how confidently it can be attributed, and at what cost.',Learning:'Converts measured results into a durable rule for future decisions.'};document.querySelectorAll('[data-chain]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-chain]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('chainInspector').innerHTML=`<b>${b.dataset.chain}</b><br>${chainDescriptions[b.dataset.chain]}`}));
const recordHumanDecision=document.getElementById('recordHumanDecision');if(recordHumanDecision)recordHumanDecision.addEventListener('click',()=>{const human=recordHumanDecision.previousElementSibling.children[2];human.querySelector('b').textContent='Approved with modification';human.querySelector('span').textContent='Rationale and timestamp stored';recordHumanDecision.textContent='✓ Human Decision Recorded';recordHumanDecision.disabled=true;toast.textContent='Human decision separated from AI recommendation and logged';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)});
const exportPlatformAudit=document.getElementById('exportPlatformAudit');if(exportPlatformAudit)exportPlatformAudit.addEventListener('click',()=>{const audit={build:'0.9',generated:new Date().toISOString(),entities:Object.keys(platformEntities),pipeline:pipelineSteps,evidence:evidenceRows,principles:['Evidence before recommendation','AI recommends; humans decide','One shared domain model'],note:'Demonstration architecture only; no live connectors.'};const blob=new Blob([JSON.stringify(audit,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='KNIP_0_9_Architecture_Audit.json';a.click();URL.revokeObjectURL(url)});

// RC1 — approved executive dashboard API hydration
function setText(id, value) {
  const element = document.getElementById(id);
  if (element && value !== undefined && value !== null) element.textContent = String(value);
}
function setWidth(id, value) {
  const element = document.getElementById(id);
  if (element && Number.isFinite(Number(value))) element.style.width = `${Math.max(0, Math.min(100, Number(value)))}%`;
}
async function hydrateExecutiveDashboard() {
  if (!window.KNIPApi) return;
  const data = await window.KNIPApi.getDashboard();
  const metrics = data.metrics || {};
  const priority = data.priorityDecision || {};
  setText('lastLogin', data.lastLogin);
  setText('metricStories', metrics.storiesValidated?.value);
  setText('metricStoriesTrend', metrics.storiesValidated?.trend);
  setText('metricCampaigns', metrics.campaignsCompleted?.value);
  setText('metricCampaignsTrend', metrics.campaignsCompleted?.trend);
  setText('metricNarratives', metrics.narrativesEmerging?.value);
  setText('metricNarrativesTrend', metrics.narrativesEmerging?.trend);
  setText('metricSentiment', metrics.audienceSentiment?.value);
  setText('metricSentimentTrend', metrics.audienceSentiment?.trend);
  setText('priorityTitle', priority.title);
  setText('prioritySummary', priority.summary);
  setText('audienceMatchValue', priority.audienceMatch !== undefined ? `${priority.audienceMatch}%` : undefined);
  setWidth('audienceMatchBar', priority.audienceMatch);
  setText('evidenceQualityValue', priority.evidenceQuality !== undefined ? `${priority.evidenceQuality}%` : undefined);
  setWidth('evidenceQualityBar', priority.evidenceQuality);
  setText('strategicImpactValue', priority.strategicImpact);
  setWidth('strategicImpactBar', priority.strategicImpactScore);
  setText('decisionReadinessValue', priority.readiness !== undefined ? `${priority.readiness}%` : undefined);
  setText('decisionReadinessState', priority.readinessState);
  setText('approvedImpact', priority.approvedImpact);
  setText('delayImpact', priority.delayImpact);
  document.body.dataset.dashboardSource = data.source || 'KNIP API';
}
hydrateExecutiveDashboard();
